//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Diagnoza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diagnoza()
        {
            this.Historia_Chorób = new ObservableCollection<Historia_Chorób>();
        }
    
        public int DiagnozaID { get; set; }
        public string Opis { get; set; }
        public int Choroba { get; set; }
    
        public virtual Choroba Choroba1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Historia_Chorób> Historia_Chorób { get; set; }
    }
}
