//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Historia_Chorób
    {
        public int Historia_ChoróbID { get; set; }
        public int Pacjent { get; set; }
        public int Pracownik { get; set; }
        public int Diagnoza { get; set; }
        public System.DateTime Zdiagnozowano { get; set; }
    
        public virtual Diagnoza Diagnoza1 { get; set; }
        public virtual Pacjent Pacjent1 { get; set; }
        public virtual Pracownik Pracownik1 { get; set; }
    }
}
