//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Pacjent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacjent()
        {
            this.Historia_Chorób = new ObservableCollection<Historia_Chorób>();
            this.Wizyta = new ObservableCollection<Wizyta>();
        }
    
        public int PacjentID { get; set; }
        public string Imiê { get; set; }
        public string Nazwisko { get; set; }
        public string Pesel { get; set; }
        public string Kod_Pocztowy { get; set; }
        public string Miejscowoœæ { get; set; }
        public string Ulica { get; set; }
        public string Nr_Domu { get; set; }
        public string Nr_Lokalu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Historia_Chorób> Historia_Chorób { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Wizyta> Wizyta { get; set; }
    }
}
