//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.ObjectModel;
    using System.Windows.Controls;

    public partial class Wizyta
    {
        public int WizytaID { get; set; }
        public int Pacjent { get; set; }
        public System.DateTime Termin { get; set; }
        public int Godzina { get; set; }
        public int Pracownik { get; set; }
        public Expander Pacjent_Exp { get; set; }

        public virtual Pacjent Pacjent1 { get; set; }
        public virtual Pracownik Pracownik1 { get; set; }
    }
}
